### DISCUSSION TITLE
No library content found

### DISCUSSION THREAD

**Discussion by dhoagland-aurorasolar** [JMBeresford/retrom#197] [Troubleshooting and debugging] [answered]
Hey there - Setting up Retrom on a new server, first time using it since the original release. I must be doing something wrong mapping my games library, but I'm not sure what. When I try to update the library it gives me an error: 

> retrom-retrom-1  | 2024-12-13T08:15:13.800783Z  WARN update_library:update_library: retrom_service::grpc::library::update_handlers: Failed to resolve platforms: Could not read directory or file: No such file or directory (os error 2)

This is hosted in Docker. If I bash into the container and go up one directory I can see the library, 'library1', I can enter into it and see all of the platform folders > game folders > roms. But I have some disconnect with the UI, because it can't see the library. An obvious culprit is that I'm using an nfs share mounted in the docker container, however, I'm hoping that isn't the issue since the library is totally accessible when I bash into the container. I think the path /library1 should be recognized internally. 

Compose: 
```yml
volumes:
  retrom_library:
    name: retrom_library
    driver_opts:
      type: nfs
      o: addr=192.168.1.32,nolock,soft
      device: :/volume1/Data/Games/library
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
      - 3000:3000
    volumes:
      - /home/user/docker/retrom/config:/config/
      - retrom_library:/library1
  retrom-db:
    container_name: retrom-db
    hostname: retrom-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /home/user/docker/retrom/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $user
      POSTGRES_PASSWORD: $password
      POSTGRES_DB: retrom
networks:
  retrom_default: {}
```

Config: 

```json
{
  "connection": {
    "port": 5101,
    "db_url": "postgres://$user:$password@retrom-db/retrom"
  },
  "content_directories": [
    {
      "path": "/library1",
      "storage_type": "MultiFileGame"
    }
  ],
  "igdb": {
    "client_secret": "$secret",
    "client_id": "$id"
  }
}
```
