### ISSUE TITLE
(root) Additional property retrom is not allowed

### ISSUE THREAD

**Issue by sladerad3** [JMBeresford/retrom#109]
Im getting this error when using the docker compose file. Is there something I'm not doing right? 

OS: Ubuntu 24.04.1 LTS 
Docker Compose version v2.29.2

I've tried it with my client id and secret, changed the postgres info to what I had setup originally. I just thought I'd try the base image on the project page and still was getting the same error. But If I pull just the image and let install it runs but without the configs from the docker compose. I have a feeling I'm missing something so simple!

<img width="668" alt="Screenshot 2024-09-20 at 11 14 46 PM" src="https://github.com/user-attachments/assets/3a2a7770-37a6-40a6-938f-93e47a7b949b">

**Comment by JMBeresford** [comment]
Ah! Those need to be under a global "services:" section. Check out the docker directory of this repository for an example of the full structure. You can also check out the docker compose file docs here: https://docs.docker.com/reference/compose-file/

**Comment by JMBeresford** [comment]
To clarify, the full file should look like this:

```yml
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
    environment:
      # IGDB API information, see the metadata-providers section above for more info
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET}

      # using the below example postgres container
      DATABASE_URL: postgres://minecraft_steve:super_secret_password@retrom-db/retrom

      # or, bring your own database:
      # DATABASE_URL: postgres://{db_user}:{db_password}@{db_host}/{db_name}
    volumes:
      - /path/to/library:/app/library

  # OPTIONAL: spin up a postgres container to use as the database. Or,
  # you can use your own postgres instance by setting DATABASE_URL above
  #
  # read the docs here: https://hub.docker.com/_/postgres
  retrom-db:
    container_name: retrom-db
    hostname: retrom-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      # to store the DB data on the host
      - /path/to/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: minecraft_steve # db user, used to connect to the db
      POSTGRES_PASSWORD: super_secret_password # db password for above user
      POSTGRES_DB: retrom # db name

```

I understand the README is not clear about this, I'll update it shortly.
