### ISSUE TITLE
Game detection went away after update

### ISSUE THREAD

**Issue by AtillatheBun** [JMBeresford/retrom#129]
After updating to the latest version from v 0.1.0 the library no longer shows and when hitting update library no games appear and and the error I get is "/retrom.LibraryService/UpdateLibrary INTERNAL: No content directories found". 
[_retrom_logs(1).txt](https://github.com/user-attachments/files/17157248/_retrom_logs.1.txt)
```
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    container_name: retrom
    ports:
      - 5101:5101
    environment:
      IGDB_CLIENT_ID: Filler
      IGDB_CLIENT_SECRET: Filler
      DATABASE_URL: postgres://Filler:Filler@retrom-db/retrom
    volumes:
      - /media/plexstorage2/Games:/media/plexstorage2/Games
      - /media/plexstorage1/Backup/Docker/retrom/config:/config
      - /media/plexstorage2/Games/:/app/library:ro
    restart: unless-stopped

  retrom-db:
    container_name: retrom-db
    hostname: retrom-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /media/plexstorage2/metadata/Data:/media/plexstorage2/metadata/Data
      - /media/plexstorage2/metadata/Data:/var/lib/postgresql/data
      - /media/plexstorage1/Backup/Docker/retrom-db/config:/config
    environment:
      POSTGRES_USER: Filler
      POSTGRES_PASSWORD: Filler
      POSTGRES_DB: retrom

  retrom-web:
    image: ghcr.io/jmberesford/retrom-web:latest
    container_name: retrom-web
    hostname: retrom-web
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      RETROM_HOST: http://retrom:5101
```
![Screenshot 2024-09-26 at 19-51-53 Retrom](https://github.com/user-attachments/assets/d5183a35-1356-4e61-a780-aa54c0756d33)
