### ISSUE TITLE
Error updating library

### ISSUE THREAD

**Issue by Szymok** [JMBeresford/retrom#147]
During updating the library i received a following error in the app:

Here is my log error:
> 2024-09-30T18:19:56.444612930Z 2024-09-30T18:19:56.444488Z WARN update_library:update_library: retrom_service::grpc::library::update_handlers: Failed to resolve platforms: Could not read directory
> 2024-09-30T18:19:56.447684986Z 2024-09-30T18:19:56.447497Z INFO update_library:update_library:spawn{name="Update Library" opts=None}:job_thread: retrom_service::grpc::jobs::job_manager: Job completed: Update Library
> 2024-09-30T18:19:56.447727739Z 2024-09-30T18:19:56.447533Z ERROR update_library:update_library:spawn{name="Update Library" opts=None}:job_thread: retrom_service::grpc::jobs::job_manager: Invalidation channel closed: SendError(f1b23bc6-641f-45a5-bd10-545fe35624df)

Here is my docker compose:

```yml
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
      - 3000:3000
    user: "1505:1505"
    volumes:
      - /home/szymon/retrom/config:/config/ # directory containing your config file
      - /home/szymon/retrom/library:/app/library
    networks:
      - retrom-network
  retrom-db:
    container_name: retrom-db
    hostname: retrom-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      # to store the DB data on the host
      - /home/szymon/retrom/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user # db user, used to connect to the db
      POSTGRES_PASSWORD: pass # db password for above user
      POSTGRES_DB: retrom # db name
    networks:
      - retrom-network


networks:
  retrom-network:
    external: false
```

Here is my config.json:

```json
{
  "connection": {
    "port": 5101,
    "db_url": "postgres://user:pass@retrom-db/retrom"
  },
  "content_directories": [
    {
      "path": "/app/library",
      "storage_type": "MultiFileGame"
    },
    {
      "path": "/app/library2",
      "storage_type": "SingleFileGame"
    }
  ],
  "igdb": {
    "client_secret": "key",
    "client_id": "key"
  }
}
```

Screenshot that i have access inside the container to the library:
![image](https://github.com/user-attachments/assets/8b5f57e7-bee1-44d6-a191-4111fb748593)
