### ISSUE TITLE
Failed to resolve platforms: Could not read directory.

### ISSUE THREAD

**Issue by Haelikor** [JMBeresford/retrom#149]
I've seen this issue elsewhere but couldn't seem to fix it using their solutions.

Error:

` 2024-10-11T03:12:37.257977Z  WARN update_library:update_library: retrom_service::grpc::library::update_handlers: Failed to resolve platforms: Could not read directory`

[[Docker-Compose]]

```yml
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
      - 3000:3000 # to access the web client
    volumes:
      - /mnt/gaming/retrom/config:/config # directory containing your config file
      - /mnt/gaming/roms:/library1 # directory containing your first library
    networks:
      - internal

  retrom-db:
    container_name: retrom-db
    hostname: retrom-db # this should match the db_url in your config file
    image: postgres:16
    restart: unless-stopped
    volumes:
      # to store the DB data on the host, change this path to any directory you like
      - /mnt/gaming/retrom/retrom_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guesswho # db user, used to connect to the db, should match the db_user in your config file
      POSTGRES_PASSWORD: specialpassword # db password for above user, should match the db_password in your config file
      POSTGRES_DB: retrom # db name, should match the db_name in your config file
    networks:
      - internal

networks:
  internal:
    external: true
```

[[Config]]
    

```json
{
  "connection": {
    "port": 5101,
    "db_url": "postgres://myusername:mycoolpassword@retrom-db/retrom"
  },
  "content_directories": [
    {
      "path": "/library1",
      "storage_type": "SingleFileGame"
    }
  ],
  "igdb": {
    "client_secret": "verycool",
    "client_id": "ultraawesome"
  }
}
```

My understanding:

Just mounting the one library type, SingleFileGame since I keep my roms one directory down from each platform. The container can access my games location, my mounts seem fine:

![image](https://github.com/user-attachments/assets/f5c53df3-74c2-4934-ba26-7e2d0188f300)
![image](https://github.com/user-attachments/assets/bab1acac-726c-4bb5-befa-d69dac59670b)

I appreciate any advice/help, neat project!

**Comment by JMBeresford** [comment]
Would you add the following to your docker compose file and restart the service to recollect the logs:

```yml
services:
  retrom:
    environment: # add this block
      - RUST_LOG=debug
```

Also can you show me the inside of your platform dirs?

Also what version of Retrom are you using here?
