### ISSUE TITLE
No way to add emulators in arch linux. 

### ISSUE THREAD

**Issue by scr1ptk1d** [JMBeresford/retrom#179]
### Describe the bug
There is no way to add emulators for arch linux.

### Steps To Reproduce
1. Install emulator via pacman
2. Execute arch client Retrom_0.4.1_amd64.AppImage 
3. Click on configuration to add emulator, womp no options to add them

### Expected behavior
A way to add emulators.

### Screenshots
![image](https://github.com/user-attachments/assets/370c0064-8e1d-4b4c-99c1-574712992ee3)

### Environment:
 - OS: 6.11.7-arch1-1 (64-bit)
 - Client: Retrom_0.4.1_amd64.AppImage 
 - Server: v0.4.1

### P.S.
- I think this project is neat and cannot wait until emulators can be server-side too

**Comment by JMBeresford** [comment]
@scr1ptk1d Have you added the emulator to the first tab yet? Emulators are added there, and are shared across all clients. The config tab is for per-client config options like the path to the executable etc. i.e. the tab you are showing will be expected to be empty if the "All Emulators" tab is also empty.

> P.S. I think this project is neat and cannot wait until emulators can be server-side too


Thanks!

**Comment by scr1ptk1d** [comment]
>Have you added the emulator to the first tab yet? Emulators are added there, and are shared across all clients. The config tab is for per-client config options like the path to the executable etc. i.e. the tab you are showing will be expected to be empty if the "All Emulators" tab is also empty.

Ohhhh, I was totally confused by the note "This is a list of all of the emulators that Retrom is tracking. In order to use these emulators locally, you will need to configure them in the Configuration tab." I think maybe for clarity's sake (to help dummies like me) it could be edited to "This is a list of all of the emulators that Retrom is tracking. In order to use these emulators locally, you will **need to make their profile here then add the paths** in the Configuration tab."
Okay, so testing I installed stella for the Atari 2600 and added the path /usr/share/applications/stella.desktop which I got via "pacman -Ql stella". When I download a file and click play the only thing happens is the client lags, nothing is in the logs, any ideas? Here is the config:
```
{
  "connection": {
    "port": 5101,
    "db_url": "postgres://snip:snip@retrom-db/retrom"
  },
  "content_directories": [
    {
      "path": "/library1",
      "storage_type": "MultiFileGame"
    }
  ],
  "igdb": {
    "client_secret": "snip",
    "client_id": "snip"
  }
}
```
and docker-compose (note it is only accessible from my tailnet):
```
configs:
  Caddyfile:
    content: |
      {
        tailscale {
          state_dir /tailscale
        }
      }
      https://games.wallaby-gopher.ts.net:443 {
        bind tailscale/games
        reverse_proxy retrom:5101
        }

volumes:
  #caddy/tailscale configs
  caddy:
  tailscale:
  #retro database
  retrom-db-data:
services:
  caddy:
    build:
        dockerfile_inline: |
          FROM caddy:2-builder AS builder
          RUN xcaddy build latest \
            --with github.com/tailscale/caddy-tailscale
          FROM caddy:2
          COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    hostname: caddy
    init: true
    container_name: "caddy"
    #networks:
    #  - nextcloud-aio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy:/data
      - tailscale:/tailscale
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    restart: unless-stopped

  #for retro games
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 3000:3000
      - 5101:5101
    volumes:
      - /media/server/server/combo:/config/ # directory containing your config file
      - /media/16d1/games:/library1 # directory containing your first library
      #- /home/minecraft_steve/library2:/library2 # directory containing your second library

  # OPTIONAL: spin up a postgres container to use as the database, if you
  # don't have one already.
  #
  # read the docs here: https://hub.docker.com/_/postgres
  retrom-db:
    container_name: retrom-db
    hostname: retrom-db # this should match the db_url in your config file
    image: postgres:16
    restart: unless-stopped
    volumes:
      # to store the DB data on the host, change this path to any directory you like
      - retrom-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: snip # db user, used to connect to the db, should match the db_user in your config file
      POSTGRES_PASSWORD: snip# db password for above user, should match the db_password in your config file
      POSTGRES_DB: retrom # db name, should match the db_name in your config file

```
![image](https://github.com/user-attachments/assets/6ad976fc-1e03-4160-bb57-05c7885ad147)

(I haven't yet figured out how to reverse proxy both ports to access the browser too)
