### ISSUE TITLE
HTTP 500 Error when updating library

### ISSUE THREAD

**Issue by Toomblr** [JMBeresford/retrom#200]
### Describe the bug
When I try to update the library, I get the error below:
<img width="398" alt="Screenshot 2024-12-16 at 09 32 49" src="https://github.com/user-attachments/assets/730ae7a8-f72c-4cd2-892f-a93b7421278e" />

### Steps To Reproduce
1. Go to `library`
2. Click on `Update library`
3. See error

### Expected behavior
An updated library

### Environment (please complete the following information _where applicable_):
 - OS: `TrueNAS SCALE Electric Eel 24.10`
 - Browser: `Firefox 133.0.3`
 - Retrom: `v0.4.8`

### Logs
Logs are not displaying any apparent errors
```
retrom-db  | 2024-12-16 08:32:33.439 UTC [1] LOG:  starting PostgreSQL 16.6 (Debian 16.6-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
retrom-db  | 2024-12-16 08:32:33.439 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
retrom-db  | 2024-12-16 08:32:33.439 UTC [1] LOG:  listening on IPv6 address "::", port 5432
retrom-db  | 2024-12-16 08:32:33.442 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
retrom-db  | 2024-12-16 08:32:33.448 UTC [29] LOG:  database system was shut down at 2024-12-16 08:32:26 UTC
retrom-db  | 2024-12-16 08:32:33.457 UTC [1] LOG:  database system is ready to accept connections
retrom     | 2024-12-16T08:32:33.779227Z  INFO retrom_service: Starting Retrom 0.4.8 service at: 0.0.0.0:5101
retrom     | ! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.5.0.tgz
retrom     | 
retrom     | > web@ preview /app/web
retrom     | > vite preview
retrom     | 
retrom     | 
retrom     | ♻️  Generating routes...
retrom     | ✅ Processed routes in 140ms
retrom     |   ➜  Local:   http://localhost:3000/
retrom     |   ➜  Network: http://172.16.2.45:3000/
```

### Additional context

docker-compose
```
services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:latest
    #    ports:
    #      - 5101:5101
    environment:
      PUID: 568
      PGID: 568
    volumes:
      - /mnt/vol2/media/retro/roms:/app/library
      - /mnt/ssd0/docker/data/retrom/config:/config/
    restart: unless-stopped
    networks:
      - npm
    depends_on:
      - retrom-db
  retrom-db:
    container_name: retrom-db
    hostname: retrom-db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /mnt/ssd0/docker/data/retromdb/config:/var/lib/postgresql/data
    environment:
      PUID: 568
      PGID: 568
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: retrom
    networks:
      - npm
networks:
  npm:
    external: true
```

config.json
```
{
    "connection": {
      "port": 5101,
      "db_url": "postgres://mypostgresusername:mypostgrespassword@retrom-db/retrom"
    },
    "content_directories": [
      {
        "path": "/app/library",
        "storage_type": "MultiFileGame"
      }
    ],
    "igdb": {
      "client_secret": "myigdbsecret",
      "client_id": "myigdbid"
    }
  }
```

**Comment by SimHat** [comment]
Same issue here.  I was looking at the api documentation for IGDB and they reference 2 different URLs https://api.igdb.com/v4/games/ and https://id.twitch.tv/oauth2/token.  I'm wondering if they changed the URL.

**Comment by aureliensoria** [comment]
Hello ! I have the same issue when updating my library.
Here are the logs related to this error in my docker container: 

> 8:33:10 AM [vite] http proxy error: /retrom.LibraryService/UpdateLibrary
Error: socket hang up
    at Socket.socketOnEnd (node:_http_client:528:25)
    at Socket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by DenowRammy** [comment]
same issue here

**Comment by JMBeresford** [comment]
@Toomblr Is your port binding really commented out, or is that an accident:

```yml
services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:latest
    #    ports:
    #      - 5101:5101
```

This is what I expect is causing your 500 error. If this is not the case, then please provide more information re: your networking situation. What IP is your retrom service running under, are you certain your client is pointed at the correct hostname + port to access the server, etc.

@SimHat The update library job does not interact w/ IGDB in any way, that is the Download Library job. IGDB is also optional, so being unable to download metadata would not lead to the inability to update the library entries and use them.
