### ISSUE TITLE
0.5.0 won't start

### ISSUE THREAD

**Issue by Toomblr** [JMBeresford/retrom#218]
### Describe the bug
After release of 0.5.0 I decided to start from scratch. But Retrom won't boot with the bare minimum docker compose.

### Steps To Reproduce
1. Make docker compose file according to [instruction](https://github.com/JMBeresford/retrom/wiki/Installation#docker):
```
services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
      - 3000:3000
    volumes:
      - /mnt/vol2/media/retro/roms:/library1
    restart: unless-stopped
```
2. run docker compose up
3. See error below

### Expected behavior
A installation screen as mentioned on the quickstart guide

### Environment (please complete the following information _where applicable_):
 - OS: `TrueNAS Scale 24.10.1`
 - Version `Retrom 0.5.0`

### Logs
```
retrom  | 2025-01-14T10:00:21.480477Z ERROR get_server{db_params=Some("?data_dir=/app/data&password_file=/app/.passwd&installation_dir=/app/psql")}: retrom_service: Could not load configuration: Config file error: Permission denied (os error 13)
retrom exited with code 0
retrom  | 2025-01-14T10:00:22.204012Z ERROR get_server{db_params=Some("?data_dir=/app/data&password_file=/app/.passwd&installation_dir=/app/psql")}: retrom_service: Could not load configuration: Config file error: Permission denied (os error 13)
```

**Comment by JMBeresford** [comment]
Ah shoot, i know what the issue is -- ill get this sorted shortly. Thanks for the report!

**Comment by vouksh** [comment]
@JMBeresford still running into the same issue on 0.5.1, here's the output from `docker-compose up`:
```console
jack@romm:/opt/docker/romm$ sudo docker-compose up
Creating network "romm_default" with the default driver
Creating retrom ... done
Attaching to retrom
retrom    | 2025-01-15T04:15:49.762880Z  INFO get_server{db_params=Some("?data_dir=/app/data&password_file=/app/.passwd&installation_dir=/app/psql")}:new: retrom_service::config: Config file does not exist, creating...
retrom    | 2025-01-15T04:15:49.763969Z ERROR get_server{db_params=Some("?data_dir=/app/data&password_file=/app/.passwd&installation_dir=/app/psql")}: retrom_service: Could not load configuration: ConfigFileError(
retrom    |     Os {
retrom    |         code: 13,
retrom    |         kind: PermissionDenied,
retrom    |         message: "Permission denied",
retrom    |     },
retrom    | )
retrom exited with code 1
```
and my docker-compose.yml:
```YAML
services:
  retrom:
    container_name: retrom
    image: ghcr.io/jmberesford/retrom-service:retrom-v0.5.1
    ports:
      - 5101:5101
      - 3000:3000
    volumes:
      - /opt/docker/romm/config:/app/config
      - /opt/docker/romm/library1:/app/library1
      - /opt/docker/romm/data:/app/data
```

This is on a fresh Ubuntu 24.04.1 
![image](https://github.com/user-attachments/assets/31cd69dc-3425-4539-ae51-e207d50491db)
