### ISSUE TITLE
Failed to save config in MacOs client

### ISSUE THREAD

**Issue by pdafoto** [JMBeresford/retrom#259]
Hi! I downloaded the MacOs client. Started initial setupo, but after setting the server parameters and the client name, when I click on Save & Relaunch, I get an error message that says "Failed to save config"

![Image](https://github.com/user-attachments/assets/e850353d-a722-48b9-8556-a9fadb9385c4)

**Comment by JMBeresford** [comment]
@pdafoto I cannot reproduce this w/ a fresh install on macOS. Can you please provide more info as requested in the [instructions for bug reports](https://github.com/JMBeresford/retrom/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by pdafoto** [comment]
Hi! Sure.

**Steps to reproduce (after uninstall and computer restart)**
1. Install and open client app
2. Select Connect to Server
3. Enter hostname (internal IP) and Port 5101, and press Next
4. Enter new client Name and press Start Fresh
5. Press Save -> Red window pops up on lower right corner (see screenshot)
6. Press Save and Relaunch -> Same window pops up every time

**Environment**
- OS: macOS 15.3.1 (24D70)
- Browser: Arc Versión 1.83.0 (58837)-RC
- Client Version: Version 0.7.11 (20250212.001537)
- Server Version: v0.7.11

**Log**: [retrom.log](https://github.com/user-attachments/files/18855131/retrom.log)

**Client config**:  [config.json](https://github.com/user-attachments/files/18855151/config.json)

**Server config**: app/config is empty (weird)
       I can download a config file from Container Manager: [retrom-retrom-1.json](https://github.com/user-attachments/files/18855258/retrom-retrom-1.json)

**Docker Compose:** 
```
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    ports:
      - 5101:5101
      - 3000:3000 # to access the web client
    volumes:
      - /volume1/ROMs/retrom:/app/library
      - retrom-config:/app/config/
      - retrom-data:/app/data/


volumes:
  retrom-data: # to persist data
  retrom-config: # to persist config
```

Hope this helps!
BTW, server is accesible through the web client and is working great!
