### ISSUE TITLE
Basic docker compose not working (from quickstart guide)

### ISSUE THREAD

**Issue by gitmotion** [JMBeresford/retrom#278]
Probably user error on my part but i've been using retrom pretty fine but noticed it hasn't been working for me after the last few updates and just got around to mentioning it here. Not sure what I'm missing but I've updated my docker compose from before (with pg database) to the updated docker compose (seen below) from the quickstart docs, and even did a fresh install of it by removing my config and library and im still getting a hanging client.

Thanks for any help! 🙏🏻

<details>
<summary>docker-compose:</summary>

```yaml
services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    container_name: retrom
    restart: unless-stopped
    ports:
      - 3210:3000 # to access the web client
      - 3211:5101
    volumes:
      - /mypath/retrom/data:/app/data/
      - /mypath/retrom/config:/app/config/ # directory containing your config file
      - /mypath/retrom/library:/app/library # directory containing your library
    labels:
      - wud.display.name=retrom
      - wud.display.icon=sh-retrom
    networks:
      - myproxy

networks:
  myproxy:
    external: true
```
</details>

<details>
<summary>Screenshots/Logs:</summary>

![Image](https://github.com/user-attachments/assets/8e7f1d80-92a7-4073-8699-f39d44d8fd2b)

![Image](https://github.com/user-attachments/assets/38374ad1-cdb9-4c70-abfa-14e9501809ff)

![Image](https://github.com/user-attachments/assets/c2139355-3322-4bdd-9554-5e863fa9e8c6)

</details>
