### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by puhtahtoe** [JMBeresford/retrom#326]
# Before Filing A Bug Report

Please be certain that this is in fact a bug that you are reporting, and -- to the best of your knowledge -- not a user error. **This issue tracker is not for support related discussion**. Please start such discourse in the [Retrom discord server](https://discord.gg/tM7VgWXCdZ) or the [discussions section](https://github.com/JMBeresford/retrom/discussions).

If your issue(s) have arisen after a recent update to Retrom ( particularly for major version updates ), please make sure you have followed any relevant steps in the respsective [migration guide(s)](https://github.com/JMBeresford/retrom/wiki/Migration-Guides)

### Describe the bug

The server configuration menu isn't saving input

### Steps To Reproduce

1. Go to server configuration
2. Change one of the options there
3. Save
4. Close the menu
5. Reopen the menu
6. See that the old configuration value is still present

### Expected behavior

The changed server configuration should be saved

### Screenshots

https://github.com/user-attachments/assets/83c0770d-877d-45c5-a803-1a157de9e94b

### Environment (please complete the following information _where applicable_)

- OS: Windows 11
- Browser: Firefox and Chrome
- Version: 0.7.24

<details>
<summary>docker-compose.yaml</summary>

```

services:
  retrom:
    image: ghcr.io/jmberesford/retrom-service:latest
    container_name: retrom
    restart: unless-stopped
    ports:
      - 5101:5101
      - 3003:3000 # to access the web client
    volumes:
      - /mnt/coppermind/games/ROMs:/ROMs
      - /home/figment/containers/retrom/config:/app/config/
      - /home/figment/containers/retrom/data:/app/data/
   
```

</details>

### Configurations

<details>
<summary>Server config</summary>

```
{
  "connection": null,
  "contentDirectories": [
    {
      "path": "/ROMs",
      "storageType": 1,
      "ignorePatterns": {
        "patterns": []
      },
      "customLibraryDefinition": {
        "definition": ""
      }
    }
  ],
  "igdb": {
    "clientId": "xxxxxxxxxxxxxx",
    "clientSecret": "xxxxxxxxxxxxxxxx"
  },
  "steam": null
}

```
</details>

This was recorded in the browser so client config is not applicable

### Logs

There are no log entries generated from the container or in the browser console when performing these actions.

### Additional context

Maybe related to #324 ?
