### ISSUE TITLE
Permissions issue when updating library

### ISSUE THREAD

**Issue by 0w1Knight** [JMBeresford/retrom#95]
Hey there! Got the containers setup and everything is looking cool. From the webUI though when I go Library > Update Library I get an error. This is setup on a Synology NAS: 

![2024-09-16_01-50-55](https://github.com/user-attachments/assets/995cee4f-8365-4a72-8f4d-ce0d6b0e0329)

Permissions issue with the library folder I think? I double checked the volume mappings and they're accurate, so not sure where the problem is. I think os error 13 is specifically a synology permissions issue so this might be out of scope of this app but figured I'd ask (no other containers are having issues), since everything seems to look right. I also tried adding UID and GID to the retrom and retrom-web containers but didn't fix things. Here is the YML with some values revoked: 

```
services:
 retrom:
  image: ghcr.io/jmberesford/retrom-service:latest
  ports:
    - 5101:5101
  environment:
    IGDB_CLIENT_ID: id
    IGDB_CLIENT_SECRET: secret
    DATABASE_URL: postgres://user:password@retrom-db/retrom

  volumes:
    - /volume1/Data/Games/library:/app/library

 retrom-db:
  container_name: retrom-db
  hostname: retrom-db
  image: postgres:16
  restart: unless-stopped
  volumes:
    - /volume1/docker/retrom/data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    POSTGRES_DB: retrom

 retrom-web:
  image: ghcr.io/jmberesford/retrom-web:latest
  container_name: retrom-web
  hostname: retrom-web
  ports:
    - 3000:3000
  environment:
    RETROM_HOST: http://192.168.1.32:5101
```

Here are the logs from the db container, its the only one updating after the containers are launched but let me know if I should provide the others too: 

[retrom-db.csv](https://github.com/user-attachments/files/17010542/retrom-db.csv)
